/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankingAccountSystem.Manipulate;

import BankingAccountSystem.Class.CustomerHistory;
import BankingAccountSystem.LoginandPage.Customer_page;
import BankingAccountSystem.Tool_Group.ConnectionClass;
import java.util.ArrayList;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HATTORI BAMBI
 */
public class Manipulate_CustomerHistory_for_Customer extends Manipulate_CustomerHistory {

    /**
     * Creates new form Manipulate_CustomerHistory_for_Customer
     */
    @Override
    public ArrayList<CustomerHistory> HistoryArrayList(){
        ArrayList<CustomerHistory> list = new ArrayList<>();
        try{
            Connection connection = ConnectionClass.connection();
            String query = "SELECT * FROM Customer_history WHERE Customer_ID=" + real_ID;
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            ResultSet rs = preparedStatement.executeQuery();
            CustomerHistory c;
            while (rs.next()){
            c = new CustomerHistory( rs.getString("Customer_ID"),
                rs.getDouble("Money_beforedo"),
                rs.getDouble("Money_afterdo"),
                rs.getString("Do"));
                list.add(c);
            }
            connection.close();
            
            
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        return list;
    }
    @Override
    public void menu(){
        dispose();
        Customer_page.main(new String[] {});
    }
    public Manipulate_CustomerHistory_for_Customer() {
        initComponents();
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        BSearch.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manipulate_CustomerHistory_for_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manipulate_CustomerHistory_for_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manipulate_CustomerHistory_for_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manipulate_CustomerHistory_for_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manipulate_CustomerHistory_for_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
