/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankingAccountSystem.Customer_Do;

import BankingAccountSystem.LoginandPage.Customer_page;
import BankingAccountSystem.Tool_Group.ConnectionClass;
import BankingAccountSystem.Tool_Group.DoClass;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author HATTORI BAMBI
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    private static String real_ID= null;
    private static String role = null;
    private static String full_name = null;
    private static double moneybefore =0.0;
    private static double moneybefore2 = 0.0;
    protected static double overdraft = 500;
    protected static int length=0;

    public static int getLength() {
        return length;
    }

    public static void setLength(int length) {
        Transfer.length = length;
    }

    public static double getMoneybefore2() {
        return moneybefore2;
    }

    public static void setMoneybefore2(double moneybefore2) {
        Transfer.moneybefore2 = moneybefore2;
    }
    public static double getMoneybefore() {
        return moneybefore;
    }

    public static void setMoneybefore(double moneybefore) {
        Transfer.moneybefore = moneybefore;
    }
    
    public static String getLFullname(){
        return full_name;
    }
    public static void setLFullName(String a){
        Transfer.full_name = a;
    }

    public static String getReal_ID() {
        return real_ID;
    }

    public static void setReal_ID(String real_ID) {
        Transfer.real_ID = real_ID;
    }

    public static String getRole() {
        return role;
    }

    public static void setRole(String role) {
        Transfer.role = role;
    }
    public Transfer() {
        initComponents();
        this.setFullName();
    }
    public void setFullName(){
        this.LFullName.setText(Transfer.getLFullname());
    }
    public void setvisible(){
        dispose();
        Customer_page.main(new String [] {});
    }
    public void checkExistID(){
        try{ 
                Connection connection = ConnectionClass.connection();
                String query = "SELECT Customer_ID FROM Customer";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()){
                    if (TID2.getText().equals(rs.getString("Customer_ID"))){
                        Transfer.setLength(length+1);
                    }
                }
                connection.close();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void transfer(){
        checkExistID();
        if (TAmount.getText().length()==0 || TID2.getText().length()==0){
            JOptionPane.showMessageDialog(null, "No Field can be empty", "Message",JOptionPane.WARNING_MESSAGE);
        }
        else {
            if (length==1){
        if (moneybefore<overdraft){
            JOptionPane.showMessageDialog(null, "You reach your limit please recharge to transfer");
            Customer_page.main(new String[] {});
        }
        else {
            try{ 
                Connection connection = ConnectionClass.connection();
                String query = "SELECT * FROM Customer WHERE Customer_ID=?";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, TID2.getText());
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()) {
                    Transfer.setMoneybefore2(rs.getDouble(7));
                }
                DoClass.transfer(TAmount.getText(), Double.toString(moneybefore), Double.toString(moneybefore2), real_ID, TID2.getText());
                Transfer.setLength(0);
                connection.close();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
        }} else {
                JOptionPane.showMessageDialog(null, "ID2 does not exist please input again", "Message", JOptionPane.WARNING_MESSAGE);
                }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TAmount = new javax.swing.JTextField();
        BReturn = new javax.swing.JButton();
        BConfirm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TID2 = new javax.swing.JTextField();
        LFullName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Amount:");

        BReturn.setText("Return");
        BReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BReturnActionPerformed(evt);
            }
        });

        BConfirm.setText("Confirm");
        BConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConfirmActionPerformed(evt);
            }
        });

        jLabel2.setText("From: ");

        jLabel3.setText("To:");

        TID2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TID2ActionPerformed(evt);
            }
        });

        LFullName.setText("Who???");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BReturn)
                        .addGap(18, 18, 18)
                        .addComponent(BConfirm))
                    .addComponent(TAmount)
                    .addComponent(TID2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(LFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(LFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TID2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BReturn)
                    .addComponent(BConfirm))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BReturnActionPerformed
        // TODO add your handling code here:
        setvisible();
    }//GEN-LAST:event_BReturnActionPerformed

    private void BConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConfirmActionPerformed
        // TODO add your handling code here:
        transfer();
        
    }//GEN-LAST:event_BConfirmActionPerformed

    private void TID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TID2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TID2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BConfirm;
    private javax.swing.JButton BReturn;
    protected javax.swing.JLabel LFullName;
    protected javax.swing.JTextField TAmount;
    protected javax.swing.JTextField TID2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
