/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankingAccountSystem.Customer_Do;

import BankingAccountSystem.LoginandPage.Staff_page;
import BankingAccountSystem.Tool_Group.ConnectionClass;
import BankingAccountSystem.Tool_Group.DoClass;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author HATTORI BAMBI
 */
public class Transfer_Staff extends Transfer {

    /**
     * Creates new form Transfer_Staff
     */
    @Override
    public void setvisible(){
        dispose();
        Staff_page.main(new String[] {});
    }
    @Override
    public void checkExistID(){
        try{ 
                Connection connection = ConnectionClass.connection();
                String query = "SELECT Customer_ID FROM Customer";
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()){
                    if ((TID2.getText().equals(rs.getString("Customer_ID"))) || (TID.getText().equals(rs.getString("Customer_ID")))){
                        Transfer.setLength(length+1);
                    }
                }
                connection.close();
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @Override
    public void transfer(){
        checkExistID();
        if (TAmount.getText().length() == 0 || TID.getText().length()==0) {
            JOptionPane.showMessageDialog(null, "No field can not be empty","Messages", JOptionPane.WARNING_MESSAGE);
            return;
        }else {
            if (length==2){
            try{
                Connection connection = ConnectionClass.connection();
                String query = "SELECT * FROM Customer WHERE Customer_ID="+TID.getText();
                PreparedStatement preparedStatement = connection.prepareStatement(query);
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()){
                    setMoneybefore(rs.getDouble(7));
                }
                if (getMoneybefore()<overdraft){
            JOptionPane.showMessageDialog(null, "You have reach your limit please recharge to do this action");
            Staff_page.main(new String[] {});
        }
                else {
                String query1 = "SELECT * FROM Customer WHERE Customer_ID=?";
                PreparedStatement preparedStatement1 = connection.prepareStatement(query1);
                preparedStatement1.setString(1, TID2.getText());
                ResultSet rs1 = preparedStatement1.executeQuery();
                while (rs1.next()) {
                    Transfer.setMoneybefore2(rs1.getDouble(7));
                }
                Transfer.setLength(0);
                DoClass.transfer(TAmount.getText(), Double.toString(getMoneybefore()), Double.toString(getMoneybefore2()), TID.getText(), TID2.getText());
                connection.close();
                }}catch (SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }} else {
                Transfer.setLength(0);
                JOptionPane.showMessageDialog(null, "ID or ID2 does not exist please input again", "Message", JOptionPane.WARNING_MESSAGE);
            }
        
                
    }}
    public Transfer_Staff() {
        initComponents();
        LFullName.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer_Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer_Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TID;
    // End of variables declaration//GEN-END:variables
}
