/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankingAccountSystem.LoginandPage;

import BankingAccountSystem.Customer_Do.Recharge;
import BankingAccountSystem.Customer_Do.Transfer;
import BankingAccountSystem.Customer_Do.Withdrawal;
import BankingAccountSystem.Manipulate.Manipulate_Customer;
import BankingAccountSystem.Manipulate.Manipulate_CustomerHistory_for_Customer;
import BankingAccountSystem.Manipulate.Manipulate_for_Customer;

/**
 *
 * @author HATTORI BAMBI
 */
public class Customer_page extends javax.swing.JFrame {

    /**
     * Creates new form Customer_page
     */
    private static String fullname=null;

    public static String getFullname() {
        return fullname;
    }

    public static void setFullname(String fullname) {
        Customer_page.fullname = fullname;
    }
    public String getLFullname(){
        return this.LFullname.getText();
    }
    public void setLFullName(){
        this.LFullname.setText(fullname);
    }
    public Customer_page() {
        initComponents();
        this.setLFullName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BCustomer = new javax.swing.JButton();
        BWithdrawal = new javax.swing.JButton();
        BRecharge = new javax.swing.JButton();
        BTransfer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LFullname = new javax.swing.JLabel();
        History = new javax.swing.JButton();
        BLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BCustomer.setText("Information");
        BCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCustomerActionPerformed(evt);
            }
        });

        BWithdrawal.setText("Withdrawal");
        BWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BWithdrawalActionPerformed(evt);
            }
        });

        BRecharge.setText("Recharge");
        BRecharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRechargeActionPerformed(evt);
            }
        });

        BTransfer.setText("Transfer");
        BTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTransferActionPerformed(evt);
            }
        });

        jLabel1.setText("DO:");

        jLabel2.setText("Welcome");

        LFullname.setText("Hi");

        History.setText("History");
        History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryActionPerformed(evt);
            }
        });

        BLogout.setText("Log out");
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(BTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BRecharge, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addComponent(BWithdrawal, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(LFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCustomer)
                    .addComponent(BRecharge))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BWithdrawal)
                    .addComponent(History))
                .addGap(18, 18, 18)
                .addComponent(BTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(BLogout)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCustomerActionPerformed
        // TODO add your handling code here:
        
        
        setVisible(false);
        Manipulate_for_Customer.main(new String[] {});
        Manipulate_Customer.setRole("0");
    }//GEN-LAST:event_BCustomerActionPerformed

    private void BRechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRechargeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Recharge.main(new String[]{});
    }//GEN-LAST:event_BRechargeActionPerformed

    private void BWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BWithdrawalActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Withdrawal.main(new String[] {});
        Withdrawal.setRole("0");
    }//GEN-LAST:event_BWithdrawalActionPerformed

    private void BTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTransferActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Transfer.main(new String[] {});
    }//GEN-LAST:event_BTransferActionPerformed

    private void HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Manipulate_CustomerHistory_for_Customer.setRole("0");
        Manipulate_CustomerHistory_for_Customer.main(new String[] {});
    }//GEN-LAST:event_HistoryActionPerformed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        Login.main(new String[] {});
    }//GEN-LAST:event_BLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCustomer;
    private javax.swing.JButton BLogout;
    private javax.swing.JButton BRecharge;
    private javax.swing.JButton BTransfer;
    private javax.swing.JButton BWithdrawal;
    private javax.swing.JButton History;
    private javax.swing.JLabel LFullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
