/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BankingAccountSystem.LoginandPage;

import BankingAccountSystem.Customer_Do.Recharge_Staff;
import BankingAccountSystem.Customer_Do.Transfer_Staff;
import BankingAccountSystem.Customer_Do.Withdrawal_Staff;
import BankingAccountSystem.Manipulate.Manipulate_Card;
import BankingAccountSystem.Manipulate.Manipulate_Customer;
import BankingAccountSystem.Manipulate.Manipulate_CustomerHistory;
import BankingAccountSystem.Manipulate.Manipulate_Staff;
import BankingAccountSystem.Manipulate.Manipulate_Staff_salary;

/**
 *
 * @author HATTORI BAMBI
 */
public class Staff_page extends javax.swing.JFrame {

    /**
     * Creates new form Staff_page
     */
    private static String fullname=null;
    public static String getFullname() {
        return fullname;
    }

    public static void setFullname(String fullname) {
        Staff_page.fullname = fullname;
    }
    public String getLFullname(){
        return this.LFullname.getText();
    }
    public void setLFullname(){
        this.LFullname.setText(fullname);
    }
    public Staff_page() {
        initComponents();
        this.setLFullname();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BCustomer = new javax.swing.JButton();
        Bcard = new javax.swing.JButton();
        Staff = new javax.swing.JButton();
        BHistory = new javax.swing.JButton();
        Staff_salary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LFullname = new javax.swing.JLabel();
        Bsignup = new javax.swing.JButton();
        Recharge = new javax.swing.JButton();
        Withdrawal = new javax.swing.JButton();
        Transfer = new javax.swing.JButton();
        BLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BCustomer.setText("Customer");
        BCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCustomerActionPerformed(evt);
            }
        });

        Bcard.setText("Card");
        Bcard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcardActionPerformed(evt);
            }
        });

        Staff.setText("Staff");
        Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffActionPerformed(evt);
            }
        });

        BHistory.setText("Customer_history");
        BHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHistoryActionPerformed(evt);
            }
        });

        Staff_salary.setText("Staff_salary");
        Staff_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_salaryActionPerformed(evt);
            }
        });

        jLabel1.setText("Welcome");

        LFullname.setText("Hi");

        Bsignup.setText("Sign Up");
        Bsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsignupActionPerformed(evt);
            }
        });

        Recharge.setText("Recharge for Customer");
        Recharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechargeActionPerformed(evt);
            }
        });

        Withdrawal.setText("Withdrawal for Customer");
        Withdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawalActionPerformed(evt);
            }
        });

        Transfer.setText("Transfer for Customer");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });

        BLogout.setText("Log out");
        BLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(Bcard)
                        .addGap(85, 85, 85)
                        .addComponent(Staff)
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BHistory)
                                .addGap(40, 40, 40)
                                .addComponent(Bsignup)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Staff_salary)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Recharge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Withdrawal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BLogout)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(LFullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bcard)
                            .addComponent(Staff)
                            .addComponent(BCustomer))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Staff_salary)
                            .addComponent(BHistory)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Bsignup)))
                .addGap(18, 18, 18)
                .addComponent(Recharge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Withdrawal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Transfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BLogout)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Staff_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_salaryActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Manipulate_Staff_salary.main(new String[] {});
    }//GEN-LAST:event_Staff_salaryActionPerformed

    private void BCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCustomerActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        Manipulate_Customer.main(new String[] {});
        Manipulate_Customer.setRole("1");
    }//GEN-LAST:event_BCustomerActionPerformed

    private void BcardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcardActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Manipulate_Card.main(new String[]{});
    }//GEN-LAST:event_BcardActionPerformed

    private void StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Manipulate_Staff.main(new String[] {});
    }//GEN-LAST:event_StaffActionPerformed

    private void BHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHistoryActionPerformed
        // TODO add your handling code here:^^
        setVisible(false);
        Manipulate_CustomerHistory.setRole("1");
        Manipulate_CustomerHistory.main(new String[] {});
    }//GEN-LAST:event_BHistoryActionPerformed

    private void BsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsignupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        SignUp.main(new String [] {});
    }//GEN-LAST:event_BsignupActionPerformed

    private void RechargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechargeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Recharge_Staff.main(new String[] {});
    }//GEN-LAST:event_RechargeActionPerformed

    private void WithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawalActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Withdrawal_Staff.main(new String[] {});
    }//GEN-LAST:event_WithdrawalActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Transfer_Staff.main(new String[] {});
    }//GEN-LAST:event_TransferActionPerformed

    private void BLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        Login.main(new String[] {});
    }//GEN-LAST:event_BLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCustomer;
    private javax.swing.JButton BHistory;
    private javax.swing.JButton BLogout;
    private javax.swing.JButton Bcard;
    private javax.swing.JButton Bsignup;
    private javax.swing.JLabel LFullname;
    private javax.swing.JButton Recharge;
    private javax.swing.JButton Staff;
    private javax.swing.JButton Staff_salary;
    private javax.swing.JButton Transfer;
    private javax.swing.JButton Withdrawal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
